version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass@
      MYSQL_DATABASE: ingress_auto
      MYSQL_USER: rouvsen
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql_db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  ms_auto:
    depends_on:
      - db
    image: rouvsen/ms_auto:1.0.ff7b644
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_db:
